from enum import Enum, auto

class Form(Enum):
    LANGUAGE = auto()
    REGION = auto()
    BRANCH = auto()
    VACANCY = auto()
    PHONE = auto()
    BIO = auto()
    BIRTH_DATE = auto()
    LIVE_PLACE = auto()
    LANGUAGES = auto()
    SOFTWARE = auto()
    FAMILY = auto()
    LAST_WORK = auto()
    LEAVE_REASON = auto()
    INTEREST = auto()
    SOURCE = auto()
    PERSONALITY = auto()
    BOOKS = auto()
    ACHIEVEMENTS = auto()
    POSITION = auto()
    TIME = auto()
    PHOTO = auto()
    CONFIRM = auto()
    SUBMIT = auto()

class AdminState(Enum):
    SELECT_REGION = auto()
    SELECT_BRANCH = auto()
    ENTER_EN = auto()
    ENTER_UZ = auto()
    ENTER_RU = auto()
    LIST_REGION = auto()
    LIST_BRANCH = auto()
    DEL_REGION = auto()
    DEL_BRANCH = auto()
    DEL_INDEX = auto()

